// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYa4FqDka0Nz4XmOApof2Xij-0w16Jw_4',
    appId: '1:662215835122:web:25c18e3cc4c41ff2493f6b',
    messagingSenderId: '662215835122',
    projectId: 'chat-and-notification-db14f',
    authDomain: 'chat-and-notification-db14f.firebaseapp.com',
    storageBucket: 'chat-and-notification-db14f.appspot.com',
    measurementId: 'G-50ZQY3LGHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWSeYdZ5WSuJG2uvM6pbcg3651zsDs5Gk',
    appId: '1:662215835122:android:749e600de8af72b3493f6b',
    messagingSenderId: '662215835122',
    projectId: 'chat-and-notification-db14f',
    storageBucket: 'chat-and-notification-db14f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdg7mRb9uftC7ZoF1mJGvSkDbUcB3wEPM',
    appId: '1:662215835122:ios:8aa55a7e2461b8fe493f6b',
    messagingSenderId: '662215835122',
    projectId: 'chat-and-notification-db14f',
    storageBucket: 'chat-and-notification-db14f.appspot.com',
    androidClientId: '662215835122-j0njvlt7doniv1d37c9oddb3jdnft84q.apps.googleusercontent.com',
    iosClientId: '662215835122-hsiu244he9q2irgmfrmp2e3jsikkr5er.apps.googleusercontent.com',
    iosBundleId: 'com.example.petApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdg7mRb9uftC7ZoF1mJGvSkDbUcB3wEPM',
    appId: '1:662215835122:ios:8aa55a7e2461b8fe493f6b',
    messagingSenderId: '662215835122',
    projectId: 'chat-and-notification-db14f',
    storageBucket: 'chat-and-notification-db14f.appspot.com',
    androidClientId: '662215835122-j0njvlt7doniv1d37c9oddb3jdnft84q.apps.googleusercontent.com',
    iosClientId: '662215835122-hsiu244he9q2irgmfrmp2e3jsikkr5er.apps.googleusercontent.com',
    iosBundleId: 'com.example.petApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYa4FqDka0Nz4XmOApof2Xij-0w16Jw_4',
    appId: '1:662215835122:web:faf58003374f8fd0493f6b',
    messagingSenderId: '662215835122',
    projectId: 'chat-and-notification-db14f',
    authDomain: 'chat-and-notification-db14f.firebaseapp.com',
    storageBucket: 'chat-and-notification-db14f.appspot.com',
    measurementId: 'G-XJLQ25YX0J',
  );

}